// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hotel.proto

package hotel

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetHotelsMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHotelsMessage) Reset()         { *m = GetHotelsMessage{} }
func (m *GetHotelsMessage) String() string { return proto.CompactTextString(m) }
func (*GetHotelsMessage) ProtoMessage()    {}
func (*GetHotelsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{0}
}

func (m *GetHotelsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHotelsMessage.Unmarshal(m, b)
}
func (m *GetHotelsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHotelsMessage.Marshal(b, m, deterministic)
}
func (m *GetHotelsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHotelsMessage.Merge(m, src)
}
func (m *GetHotelsMessage) XXX_Size() int {
	return xxx_messageInfo_GetHotelsMessage.Size(m)
}
func (m *GetHotelsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHotelsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetHotelsMessage proto.InternalMessageInfo

type GetHotelsResponse struct {
	Hotels               []*Hotel `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHotelsResponse) Reset()         { *m = GetHotelsResponse{} }
func (m *GetHotelsResponse) String() string { return proto.CompactTextString(m) }
func (*GetHotelsResponse) ProtoMessage()    {}
func (*GetHotelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{1}
}

func (m *GetHotelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHotelsResponse.Unmarshal(m, b)
}
func (m *GetHotelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHotelsResponse.Marshal(b, m, deterministic)
}
func (m *GetHotelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHotelsResponse.Merge(m, src)
}
func (m *GetHotelsResponse) XXX_Size() int {
	return xxx_messageInfo_GetHotelsResponse.Size(m)
}
func (m *GetHotelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHotelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHotelsResponse proto.InternalMessageInfo

func (m *GetHotelsResponse) GetHotels() []*Hotel {
	if m != nil {
		return m.Hotels
	}
	return nil
}

type Hotel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HotelName            string   `protobuf:"bytes,2,opt,name=hotel_name,json=hotelName,proto3" json:"hotel_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hotel) Reset()         { *m = Hotel{} }
func (m *Hotel) String() string { return proto.CompactTextString(m) }
func (*Hotel) ProtoMessage()    {}
func (*Hotel) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{2}
}

func (m *Hotel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hotel.Unmarshal(m, b)
}
func (m *Hotel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hotel.Marshal(b, m, deterministic)
}
func (m *Hotel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hotel.Merge(m, src)
}
func (m *Hotel) XXX_Size() int {
	return xxx_messageInfo_Hotel.Size(m)
}
func (m *Hotel) XXX_DiscardUnknown() {
	xxx_messageInfo_Hotel.DiscardUnknown(m)
}

var xxx_messageInfo_Hotel proto.InternalMessageInfo

func (m *Hotel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hotel) GetHotelName() string {
	if m != nil {
		return m.HotelName
	}
	return ""
}

type GetPlansMessage struct {
	HotelId              int64    `protobuf:"varint,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlansMessage) Reset()         { *m = GetPlansMessage{} }
func (m *GetPlansMessage) String() string { return proto.CompactTextString(m) }
func (*GetPlansMessage) ProtoMessage()    {}
func (*GetPlansMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{3}
}

func (m *GetPlansMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlansMessage.Unmarshal(m, b)
}
func (m *GetPlansMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlansMessage.Marshal(b, m, deterministic)
}
func (m *GetPlansMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlansMessage.Merge(m, src)
}
func (m *GetPlansMessage) XXX_Size() int {
	return xxx_messageInfo_GetPlansMessage.Size(m)
}
func (m *GetPlansMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlansMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlansMessage proto.InternalMessageInfo

func (m *GetPlansMessage) GetHotelId() int64 {
	if m != nil {
		return m.HotelId
	}
	return 0
}

type GetPlansResponse struct {
	Plans                []*Plan  `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlansResponse) Reset()         { *m = GetPlansResponse{} }
func (m *GetPlansResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlansResponse) ProtoMessage()    {}
func (*GetPlansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{4}
}

func (m *GetPlansResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlansResponse.Unmarshal(m, b)
}
func (m *GetPlansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlansResponse.Marshal(b, m, deterministic)
}
func (m *GetPlansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlansResponse.Merge(m, src)
}
func (m *GetPlansResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlansResponse.Size(m)
}
func (m *GetPlansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlansResponse proto.InternalMessageInfo

func (m *GetPlansResponse) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

type Plan struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HotelId              int64                `protobuf:"varint,2,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Total                uint64               `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Available            uint64               `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	Cost                 uint64               `protobuf:"varint,7,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{5}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Plan) GetHotelId() int64 {
	if m != nil {
		return m.HotelId
	}
	return 0
}

func (m *Plan) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Plan) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Plan) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Plan) GetAvailable() uint64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *Plan) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type ReserveHotellMessage struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId               int64    `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	SequenceId           string   `protobuf:"bytes,3,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveHotellMessage) Reset()         { *m = ReserveHotellMessage{} }
func (m *ReserveHotellMessage) String() string { return proto.CompactTextString(m) }
func (*ReserveHotellMessage) ProtoMessage()    {}
func (*ReserveHotellMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{6}
}

func (m *ReserveHotellMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveHotellMessage.Unmarshal(m, b)
}
func (m *ReserveHotellMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveHotellMessage.Marshal(b, m, deterministic)
}
func (m *ReserveHotellMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveHotellMessage.Merge(m, src)
}
func (m *ReserveHotellMessage) XXX_Size() int {
	return xxx_messageInfo_ReserveHotellMessage.Size(m)
}
func (m *ReserveHotellMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveHotellMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveHotellMessage proto.InternalMessageInfo

func (m *ReserveHotellMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReserveHotellMessage) GetPlanId() int64 {
	if m != nil {
		return m.PlanId
	}
	return 0
}

func (m *ReserveHotellMessage) GetSequenceId() string {
	if m != nil {
		return m.SequenceId
	}
	return ""
}

type ReserveHotelResponse struct {
	ReservationId        int64    `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveHotelResponse) Reset()         { *m = ReserveHotelResponse{} }
func (m *ReserveHotelResponse) String() string { return proto.CompactTextString(m) }
func (*ReserveHotelResponse) ProtoMessage()    {}
func (*ReserveHotelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{7}
}

func (m *ReserveHotelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveHotelResponse.Unmarshal(m, b)
}
func (m *ReserveHotelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveHotelResponse.Marshal(b, m, deterministic)
}
func (m *ReserveHotelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveHotelResponse.Merge(m, src)
}
func (m *ReserveHotelResponse) XXX_Size() int {
	return xxx_messageInfo_ReserveHotelResponse.Size(m)
}
func (m *ReserveHotelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveHotelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveHotelResponse proto.InternalMessageInfo

func (m *ReserveHotelResponse) GetReservationId() int64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

type CancelHotelMessage struct {
	ReservationId        int64    `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelHotelMessage) Reset()         { *m = CancelHotelMessage{} }
func (m *CancelHotelMessage) String() string { return proto.CompactTextString(m) }
func (*CancelHotelMessage) ProtoMessage()    {}
func (*CancelHotelMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{8}
}

func (m *CancelHotelMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelHotelMessage.Unmarshal(m, b)
}
func (m *CancelHotelMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelHotelMessage.Marshal(b, m, deterministic)
}
func (m *CancelHotelMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelHotelMessage.Merge(m, src)
}
func (m *CancelHotelMessage) XXX_Size() int {
	return xxx_messageInfo_CancelHotelMessage.Size(m)
}
func (m *CancelHotelMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelHotelMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CancelHotelMessage proto.InternalMessageInfo

func (m *CancelHotelMessage) GetReservationId() int64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

type CancelHotelResponse struct {
	Restult              bool     `protobuf:"varint,1,opt,name=restult,proto3" json:"restult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelHotelResponse) Reset()         { *m = CancelHotelResponse{} }
func (m *CancelHotelResponse) String() string { return proto.CompactTextString(m) }
func (*CancelHotelResponse) ProtoMessage()    {}
func (*CancelHotelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{9}
}

func (m *CancelHotelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelHotelResponse.Unmarshal(m, b)
}
func (m *CancelHotelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelHotelResponse.Marshal(b, m, deterministic)
}
func (m *CancelHotelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelHotelResponse.Merge(m, src)
}
func (m *CancelHotelResponse) XXX_Size() int {
	return xxx_messageInfo_CancelHotelResponse.Size(m)
}
func (m *CancelHotelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelHotelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelHotelResponse proto.InternalMessageInfo

func (m *CancelHotelResponse) GetRestult() bool {
	if m != nil {
		return m.Restult
	}
	return false
}

type GetReservationsMessage struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReservationsMessage) Reset()         { *m = GetReservationsMessage{} }
func (m *GetReservationsMessage) String() string { return proto.CompactTextString(m) }
func (*GetReservationsMessage) ProtoMessage()    {}
func (*GetReservationsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{10}
}

func (m *GetReservationsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationsMessage.Unmarshal(m, b)
}
func (m *GetReservationsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationsMessage.Marshal(b, m, deterministic)
}
func (m *GetReservationsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationsMessage.Merge(m, src)
}
func (m *GetReservationsMessage) XXX_Size() int {
	return xxx_messageInfo_GetReservationsMessage.Size(m)
}
func (m *GetReservationsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationsMessage proto.InternalMessageInfo

func (m *GetReservationsMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetReservationsResponse struct {
	Reservations         []*Reservation `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetReservationsResponse) Reset()         { *m = GetReservationsResponse{} }
func (m *GetReservationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetReservationsResponse) ProtoMessage()    {}
func (*GetReservationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{11}
}

func (m *GetReservationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationsResponse.Unmarshal(m, b)
}
func (m *GetReservationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationsResponse.Marshal(b, m, deterministic)
}
func (m *GetReservationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationsResponse.Merge(m, src)
}
func (m *GetReservationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetReservationsResponse.Size(m)
}
func (m *GetReservationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationsResponse proto.InternalMessageInfo

func (m *GetReservationsResponse) GetReservations() []*Reservation {
	if m != nil {
		return m.Reservations
	}
	return nil
}

type Reservation struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId               int64    `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SequenceId           string   `protobuf:"bytes,4,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reservation) Reset()         { *m = Reservation{} }
func (m *Reservation) String() string { return proto.CompactTextString(m) }
func (*Reservation) ProtoMessage()    {}
func (*Reservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{12}
}

func (m *Reservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reservation.Unmarshal(m, b)
}
func (m *Reservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reservation.Marshal(b, m, deterministic)
}
func (m *Reservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reservation.Merge(m, src)
}
func (m *Reservation) XXX_Size() int {
	return xxx_messageInfo_Reservation.Size(m)
}
func (m *Reservation) XXX_DiscardUnknown() {
	xxx_messageInfo_Reservation.DiscardUnknown(m)
}

var xxx_messageInfo_Reservation proto.InternalMessageInfo

func (m *Reservation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reservation) GetPlanId() int64 {
	if m != nil {
		return m.PlanId
	}
	return 0
}

func (m *Reservation) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Reservation) GetSequenceId() string {
	if m != nil {
		return m.SequenceId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetHotelsMessage)(nil), "GetHotelsMessage")
	proto.RegisterType((*GetHotelsResponse)(nil), "GetHotelsResponse")
	proto.RegisterType((*Hotel)(nil), "Hotel")
	proto.RegisterType((*GetPlansMessage)(nil), "GetPlansMessage")
	proto.RegisterType((*GetPlansResponse)(nil), "GetPlansResponse")
	proto.RegisterType((*Plan)(nil), "Plan")
	proto.RegisterType((*ReserveHotellMessage)(nil), "ReserveHotellMessage")
	proto.RegisterType((*ReserveHotelResponse)(nil), "ReserveHotelResponse")
	proto.RegisterType((*CancelHotelMessage)(nil), "CancelHotelMessage")
	proto.RegisterType((*CancelHotelResponse)(nil), "CancelHotelResponse")
	proto.RegisterType((*GetReservationsMessage)(nil), "GetReservationsMessage")
	proto.RegisterType((*GetReservationsResponse)(nil), "GetReservationsResponse")
	proto.RegisterType((*Reservation)(nil), "Reservation")
}

func init() { proto.RegisterFile("hotel.proto", fileDescriptor_169099f938a8a4b0) }

var fileDescriptor_169099f938a8a4b0 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x13, 0xc7, 0x69, 0xc6, 0xa1, 0xb4, 0xd3, 0x42, 0x8d, 0xf9, 0xa8, 0xb5, 0x12, 0x52,
	0x0e, 0x68, 0x43, 0x5b, 0xc4, 0x01, 0x04, 0x17, 0x24, 0x4a, 0x84, 0x40, 0xc8, 0x70, 0x47, 0x9b,
	0x78, 0x08, 0x96, 0x1c, 0xdb, 0x78, 0x37, 0xf9, 0x73, 0xfc, 0x04, 0xfe, 0x14, 0xf2, 0xba, 0x76,
	0x36, 0x4e, 0x2a, 0xb8, 0x65, 0xde, 0xcc, 0xec, 0x3c, 0xbf, 0x37, 0x13, 0x70, 0x7f, 0x66, 0x8a,
	0x12, 0x9e, 0x17, 0x99, 0xca, 0xfc, 0xf3, 0x45, 0x96, 0x2d, 0x12, 0x9a, 0xe8, 0x68, 0xb6, 0xfa,
	0x31, 0x51, 0xf1, 0x92, 0xa4, 0x12, 0xcb, 0xbc, 0x2a, 0x60, 0x08, 0x47, 0xd7, 0xa4, 0x3e, 0x94,
	0x2d, 0xf2, 0x13, 0x49, 0x29, 0x16, 0xc4, 0xae, 0xe0, 0xb8, 0xc1, 0x42, 0x92, 0x79, 0x96, 0x4a,
	0xc2, 0x27, 0xe0, 0xe8, 0x87, 0xa5, 0x67, 0x05, 0xbd, 0xb1, 0x7b, 0xe9, 0x70, 0x5d, 0x10, 0xde,
	0xa0, 0xec, 0x25, 0xf4, 0x35, 0x80, 0x87, 0xd0, 0x8d, 0x23, 0xcf, 0x0a, 0xac, 0x71, 0x2f, 0xec,
	0xc6, 0x11, 0x3e, 0x06, 0xd0, 0x25, 0xdf, 0x53, 0xb1, 0x24, 0xaf, 0x1b, 0x58, 0xe3, 0x61, 0x38,
	0xd4, 0xc8, 0x67, 0xb1, 0x24, 0xf6, 0x0c, 0xee, 0x5e, 0x93, 0xfa, 0x92, 0x88, 0xb4, 0x9e, 0x8f,
	0x0f, 0xe0, 0xa0, 0xea, 0x68, 0xde, 0x19, 0xe8, 0x78, 0x1a, 0xb1, 0x89, 0xa6, 0xab, 0xab, 0x1b,
	0x66, 0x0f, 0xa1, 0x9f, 0x97, 0xc0, 0x0d, 0xb1, 0x3e, 0x2f, 0xd3, 0x61, 0x85, 0xb1, 0x3f, 0x16,
	0xd8, 0x65, 0xbc, 0x43, 0xcb, 0x1c, 0xd2, 0xdd, 0x1a, 0x82, 0x01, 0xb8, 0x11, 0xc9, 0x79, 0x11,
	0xe7, 0x2a, 0xce, 0x52, 0xaf, 0xa7, 0x29, 0x9b, 0x10, 0x72, 0xb0, 0x23, 0xa1, 0xc8, 0xb3, 0x03,
	0x6b, 0xec, 0x5e, 0xfa, 0xbc, 0x52, 0x99, 0xd7, 0x2a, 0xf3, 0x6f, 0xb5, 0xca, 0xa1, 0xae, 0xc3,
	0x53, 0xe8, 0xab, 0x4c, 0x89, 0xc4, 0xeb, 0x07, 0xd6, 0xd8, 0x0e, 0xab, 0x00, 0x1f, 0xc1, 0x50,
	0xac, 0x45, 0x9c, 0x88, 0x59, 0x42, 0x9e, 0xa3, 0x33, 0x1b, 0x00, 0x11, 0xec, 0x79, 0x26, 0x95,
	0x37, 0xd0, 0x09, 0xfd, 0x9b, 0xc5, 0x70, 0x1a, 0x92, 0xa4, 0x62, 0x4d, 0x5a, 0xeb, 0xa4, 0x56,
	0xec, 0x0c, 0x06, 0x2b, 0x49, 0xc5, 0x46, 0x30, 0xa7, 0x0c, 0xa7, 0x51, 0x99, 0x28, 0x75, 0xd8,
	0x7c, 0xa4, 0x53, 0x86, 0xd3, 0x08, 0xcf, 0xc1, 0x95, 0xf4, 0x6b, 0x45, 0xe9, 0x9c, 0xca, 0x64,
	0xf5, 0x8d, 0x50, 0x43, 0xd3, 0x88, 0xbd, 0xd9, 0x1e, 0xd5, 0xa8, 0xfd, 0x14, 0x0e, 0x0b, 0x8d,
	0x8b, 0x52, 0x89, 0xcd, 0xc4, 0x3b, 0x06, 0x3a, 0x8d, 0xd8, 0x6b, 0xc0, 0x77, 0x22, 0x9d, 0x53,
	0xa2, 0xbb, 0x6b, 0x9e, 0xff, 0xd9, 0x3c, 0x81, 0x13, 0xa3, 0xb9, 0x19, 0xed, 0xc1, 0xa0, 0x20,
	0xa9, 0x56, 0x89, 0xd2, 0x6d, 0x07, 0x61, 0x1d, 0xb2, 0x0b, 0xb8, 0x7f, 0x4d, 0x2a, 0xdc, 0x3c,
	0x22, 0xff, 0xa5, 0x0c, 0xfb, 0x08, 0x67, 0xad, 0x96, 0x66, 0xce, 0x73, 0x18, 0x19, 0x7c, 0xea,
	0xbd, 0x1a, 0x71, 0xa3, 0x38, 0xdc, 0xaa, 0x60, 0x39, 0xb8, 0x46, 0x72, 0x67, 0xd7, 0x6e, 0x75,
	0xc1, 0x60, 0xd7, 0xdb, 0xf2, 0xad, 0x65, 0x8f, 0xdd, 0xb6, 0xe7, 0xf2, 0x77, 0x17, 0x46, 0x5a,
	0x9d, 0xaf, 0x54, 0xac, 0xe3, 0x39, 0xe1, 0x0b, 0x18, 0x36, 0x47, 0x8b, 0xc7, 0xbc, 0x7d, 0xd4,
	0x3e, 0xf2, 0x9d, 0x9b, 0x66, 0x1d, 0xbc, 0x80, 0x83, 0xfa, 0x9e, 0xf0, 0x88, 0xb7, 0x0e, 0xd1,
	0x3f, 0xe6, 0xed, 0x63, 0x63, 0x1d, 0x7c, 0x0b, 0x23, 0x73, 0x31, 0xf0, 0x1e, 0xdf, 0xb7, 0x92,
	0xfe, 0x36, 0x6c, 0xf4, 0xbf, 0x02, 0xd7, 0x30, 0x17, 0x4f, 0xf8, 0xee, 0x9e, 0xf8, 0xa7, 0x7c,
	0x8f, 0xff, 0xac, 0x83, 0xef, 0xf5, 0x9f, 0x85, 0x69, 0x1a, 0x9e, 0xf1, 0xfd, 0xce, 0xfb, 0x1e,
	0xbf, 0xc5, 0x5f, 0xd6, 0x99, 0x39, 0xfa, 0x52, 0xaf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x60,
	0x1b, 0xbe, 0xb4, 0x2c, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HotelServiceClient is the client API for HotelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HotelServiceClient interface {
	GetHotels(ctx context.Context, in *GetHotelsMessage, opts ...grpc.CallOption) (*GetHotelsResponse, error)
	GetPlans(ctx context.Context, in *GetPlansMessage, opts ...grpc.CallOption) (*GetPlansResponse, error)
	ReserveHotel(ctx context.Context, in *ReserveHotellMessage, opts ...grpc.CallOption) (*ReserveHotelResponse, error)
	CancelHotel(ctx context.Context, in *CancelHotelMessage, opts ...grpc.CallOption) (*CancelHotelResponse, error)
	GetReservations(ctx context.Context, in *GetReservationsMessage, opts ...grpc.CallOption) (*GetReservationsResponse, error)
}

type hotelServiceClient struct {
	cc *grpc.ClientConn
}

func NewHotelServiceClient(cc *grpc.ClientConn) HotelServiceClient {
	return &hotelServiceClient{cc}
}

func (c *hotelServiceClient) GetHotels(ctx context.Context, in *GetHotelsMessage, opts ...grpc.CallOption) (*GetHotelsResponse, error) {
	out := new(GetHotelsResponse)
	err := c.cc.Invoke(ctx, "/HotelService/GetHotels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelServiceClient) GetPlans(ctx context.Context, in *GetPlansMessage, opts ...grpc.CallOption) (*GetPlansResponse, error) {
	out := new(GetPlansResponse)
	err := c.cc.Invoke(ctx, "/HotelService/GetPlans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelServiceClient) ReserveHotel(ctx context.Context, in *ReserveHotellMessage, opts ...grpc.CallOption) (*ReserveHotelResponse, error) {
	out := new(ReserveHotelResponse)
	err := c.cc.Invoke(ctx, "/HotelService/ReserveHotel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelServiceClient) CancelHotel(ctx context.Context, in *CancelHotelMessage, opts ...grpc.CallOption) (*CancelHotelResponse, error) {
	out := new(CancelHotelResponse)
	err := c.cc.Invoke(ctx, "/HotelService/CancelHotel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelServiceClient) GetReservations(ctx context.Context, in *GetReservationsMessage, opts ...grpc.CallOption) (*GetReservationsResponse, error) {
	out := new(GetReservationsResponse)
	err := c.cc.Invoke(ctx, "/HotelService/GetReservations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotelServiceServer is the server API for HotelService service.
type HotelServiceServer interface {
	GetHotels(context.Context, *GetHotelsMessage) (*GetHotelsResponse, error)
	GetPlans(context.Context, *GetPlansMessage) (*GetPlansResponse, error)
	ReserveHotel(context.Context, *ReserveHotellMessage) (*ReserveHotelResponse, error)
	CancelHotel(context.Context, *CancelHotelMessage) (*CancelHotelResponse, error)
	GetReservations(context.Context, *GetReservationsMessage) (*GetReservationsResponse, error)
}

func RegisterHotelServiceServer(s *grpc.Server, srv HotelServiceServer) {
	s.RegisterService(&_HotelService_serviceDesc, srv)
}

func _HotelService_GetHotels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotelsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).GetHotels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HotelService/GetHotels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).GetHotels(ctx, req.(*GetHotelsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotelService_GetPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlansMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).GetPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HotelService/GetPlans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).GetPlans(ctx, req.(*GetPlansMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotelService_ReserveHotel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveHotellMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).ReserveHotel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HotelService/ReserveHotel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).ReserveHotel(ctx, req.(*ReserveHotellMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotelService_CancelHotel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelHotelMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).CancelHotel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HotelService/CancelHotel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).CancelHotel(ctx, req.(*CancelHotelMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotelService_GetReservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReservationsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).GetReservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HotelService/GetReservations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).GetReservations(ctx, req.(*GetReservationsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _HotelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HotelService",
	HandlerType: (*HotelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHotels",
			Handler:    _HotelService_GetHotels_Handler,
		},
		{
			MethodName: "GetPlans",
			Handler:    _HotelService_GetPlans_Handler,
		},
		{
			MethodName: "ReserveHotel",
			Handler:    _HotelService_ReserveHotel_Handler,
		},
		{
			MethodName: "CancelHotel",
			Handler:    _HotelService_CancelHotel_Handler,
		},
		{
			MethodName: "GetReservations",
			Handler:    _HotelService_GetReservations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hotel.proto",
}
